apps/blog/urls.py
from django.urls import path
from .views import blog_views, blog_single, views_up

app_name = 'blog'

urlpatterns = [
    path('', blog_views, name="blog"),
    path('article/<int:pk>/', blog_single, name="blog-single"),
    path('views_up/<int:pk>/', views_up, name="views_up"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.resume.urls', namespace='resume')),
    path('blog/', include('apps.blog.urls', namespace='blog')),
    path('comment/', include('apps.comment.urls', namespace='comment')),
    path('contact/', include('apps.contact.urls', namespace='contact')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/blog/models.py
from django.db import models


# Create your models here.

class Category(models.Model):
    title = models.CharField(max_length=221)

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.title


class Tag(models.Model):
    title = models.CharField(max_length=221)

    def __str__(self):
        return self.title


class Blog(models.Model):
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, related_name='cat1')
    title = models.CharField(max_length=221)
    image = models.ImageField(upload_to='blog/')
    content = models.TextField()
    tags = models.ManyToManyField(Tag)
    views = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

apps/comment/models.py
from django.db import models
from apps.blog.models import Blog
# Create your models here.


class CommentModel(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    name = models.CharField(max_length=221)
    avatar = models.ImageField(upload_to='comment', null=True, blank=True)
    email = models.EmailField()
    website = models.CharField(max_length=221)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

apps/blog/views.py
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, redirect
from .models import Blog, Tag, Category
from apps.comment.models import CommentModel

# Create your views here.
from apps.comment.forms import CommentForm


def blog_views(request):
    blog_list = Blog.objects.all()

    q = request.GET.get("q")
    if q:
        blog_list = Blog.objects.filter(title__icontains=q)

    tag = request.GET.get("tag")
    if tag:
        blog_list = Blog.objects.filter(tags__title__exact=tag)

    category = request.GET.get("category")
    if category:
        blog_list = Blog.objects.filter(category__title__exact=category)

    page_number = request.GET.get("page")
    p = Paginator(blog_list, 1)
    try:
        page_obj = p.get_page(page_number)
    except PageNotAnInteger:
        page_obj = p.get_page(1)
    except EmptyPage:
        page_obj = p.get_page(p.num_pages)

    context = {"blog_list": blog_list, "page_obj": page_obj}
    return render(request, 'blog.html', context)


def views_up(request, pk):
    blog = Blog.objects.get(id=pk)
    blog.views += 1
    blog.save()
    return redirect("blog:blog-single", blog.pk)


def blog_single(request, pk):
    blog_obj = Blog.objects.get(id=pk)
    recent_articles = Blog.objects.all().order_by("-created_at")[:3]
    categories = Category.objects.all()
    for category in categories:
        category.n = len(Blog.objects.filter(category=category))
    tags = Tag.objects.all()

    form = CommentForm()
    if request.method == "POST":
        form = CommentForm(request.POST, request.FILES)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.blog = blog_obj
            obj.save()
            return redirect('.')

    context = {"blog_obj": blog_obj, "tags": tags, "form": form,
               "recent_articles": recent_articles,
               "categories": categories}
    return render(request, 'single.html', context)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<!-- Mirrored from preview.colorlib.com/theme/clyde/ by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 10 Sep 2022 15:13:08 GMT -->
<head>
    <title>Clyde - Free Bootstrap 4 Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet"
          href="{% static 'css/animate.css%2bowl.carousel.min.css%2bowl.theme.default.min.css%2bmagnific-popup.css%2bflaticon.css%2bstyle.css.pagespeed.cc.mTDtO8mxmT.css' %}"/>
    <script nonce="f760fe1e-f669-4b54-8291-c0f7ae624585">
        (function (w, d) {
            !function (a, e, t, r) {
                a.zarazData = a.zarazData || {};
                a.zarazData.executed = [];
                a.zaraz = {deferred: []};
                a.zaraz.q = [];
                a.zaraz._f = function (e) {
                    return function () {
                        var t = Array.prototype.slice.call(arguments);
                        a.zaraz.q.push({m: e, a: t})
                    }
                };
                for (const e of ["track", "set", "ecommerce", "debug"]) a.zaraz[e] = a.zaraz._f(e);
                a.zaraz.init = () => {
                    var t = e.getElementsByTagName(r)[0], z = e.createElement(r),
                        n = e.getElementsByTagName("title")[0];
                    n && (a.zarazData.t = e.getElementsByTagName("title")[0].text);
                    a.zarazData.x = Math.random();
                    a.zarazData.w = a.screen.width;
                    a.zarazData.h = a.screen.height;
                    a.zarazData.j = a.innerHeight;
                    a.zarazData.e = a.innerWidth;
                    a.zarazData.l = a.location.href;
                    a.zarazData.r = e.referrer;
                    a.zarazData.k = a.screen.colorDepth;
                    a.zarazData.n = e.characterSet;
                    a.zarazData.o = (new Date).getTimezoneOffset();
                    a.zarazData.q = [];
                    for (; a.zaraz.q.length;) {
                        const e = a.zaraz.q.shift();
                        a.zarazData.q.push(e)
                    }
                    z.defer = !0;
                    for (const e of [localStorage, sessionStorage]) Object.keys(e || {}).filter((a => a.startsWith("_zaraz_"))).forEach((t => {
                        try {
                            a.zarazData["z_" + t.slice(7)] = JSON.parse(e.getItem(t))
                        } catch {
                            a.zarazData["z_" + t.slice(7)] = e.getItem(t)
                        }
                    }));
                    z.referrerPolicy = "origin";
                    z.src = "https://preview.colorlib.com/cdn-cgi/zaraz/s.js?z=" + btoa(encodeURIComponent(JSON.stringify(a.zarazData)));
                    t.parentNode.insertBefore(z, t)
                };
                ["complete", "interactive"].includes(e.readyState) ? zaraz.init() : a.addEventListener("DOMContentLoaded", zaraz.init)
            }(w, d, 0, "script");
        })(window, document);

    </script>
    <style>
        .messages {
            width: 80%;
            padding: 50px 30px;
            background-color: #28a745;
            color: #ced4da;
            position: absolute;
            top: 50%;
            left: 50%;
            text-align: center;
            transform: translate(-50%, -50%);
            z-index: 999;
            border: 1px solid #28a745;
            border-radius: 15px;
            display: block;
            transition-duration: 1s;
            animation-name: fadeout;
            animation-duration: 2s;
            animation-delay: 0.5s;
            animation-fill-mode: forwards;
        }

        @-webkit-keyframes fadeout {
            to {
                visibility: hidden;
            }
        }

        @keyframes fadeout {
            to {
                visibility: hidden;
            }
        }

    </style>

</head>

<body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">
{% include 'navbar.html' %}
{% if messages %}
    {% for message in messages %}
        <div class="messages alert alert-success" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}
{% block content %}

{% endblock content %}
{% include 'footer.html' %}


<div id="ftco-loader" class="show fullscreen">
    <svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                stroke="#F96D00"/>
    </svg>
</div>


<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery-migrate-3.0.1.min.js%2bpopper.min.js%2bbootstrap.min.js.pagespeed.jc.b3XFzyXpnj.js' %}"></script>
<script>eval(mod_pagespeed_VTudpog2tl);</script>
<script>eval(mod_pagespeed_0BZUninGge);</script>
<script>eval(mod_pagespeed_maW2n$DGnT);</script>
<script src="{% static 'js/jquery.easing.1.3.js%2bjquery.waypoints.min.js%2bjquery.stellar.min.js%2bowl.carousel.min.js.pagespeed.jc.QHGgRmwzcA.js' %}"></script>
<script>eval(mod_pagespeed_I3M3l3IXUe);</script>
<script>eval(mod_pagespeed_SHbcZVIzU3);</script>
<script>eval(mod_pagespeed_6Kl8EjUf4r);</script>
<script>eval(mod_pagespeed_NUpn82VALA);</script>
<script src="{% static 'js/jquery.magnific-popup.min.js%2bjquery.animateNumber.min.js%2bscrollax.min.js%2bgoogle-map.js%2bmain.js.pagespeed.jc.CCB18YZEB2.js' %}"></script>
<script>eval(mod_pagespeed__1sR0D8Ldf);</script>
<script>eval(mod_pagespeed_q8h5aKLL7o);</script>
<script>eval(mod_pagespeed_QezhYewLgh);</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&amp;sensor=false"></script>
<script>eval(mod_pagespeed_1GWiyte$dv);</script>
<script>eval(mod_pagespeed_fKcZE44mYf);</script>

<script>
    {#$('.messages').delay(50000).css('display','none');#}
    console.log('messages ishlayappti')
</script>

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
        dataLayer.push(arguments);
    }

    gtag('js', new Date());

    gtag('config', 'UA-23581568-13');


</script>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js/v652eace1692a40cfa3763df669d7439c1639079717194"
        integrity="sha512-Gi7xpJR8tSkrpF7aordPZQlW2DLtzUlZcumS8dMQjwDHEnw9I7ZLyiOj/6tZStRBGtGgN6ceN6cMH8z7etPGlw=="
        data-cf-beacon='{"rayId":"74891b16291edd98","token":"cd0b4b3a733644fc843ef0b185f98241","version":"2022.8.1","si":100}'
        crossorigin="anonymous"></script>
</body>

<!-- Mirrored from preview.colorlib.com/theme/clyde/ by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 10 Sep 2022 15:13:35 GMT -->
</html>

templates/blog.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Blog{% endblock %}
{% load params_tags %}

{% block content %}
<section class="ftco-section bg-light" id="blog-section">
    <div class="container">
        <div class="row justify-content-center mb-5 pb-5">
            <div class="col-md-7 heading-section text-center ftco-animate">
                <span class="subheading">Blog</span>
                <h2 class="mb-4">Our Blog</h2>
                <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia</p>
            </div>
        </div>
        <div class="row d-flex">
            {% for item in page_obj %}
            <div class="col-md-4 d-flex ftco-animate">
                <div class="blog-entry justify-content-end">
                    <a href="{% url 'blog:views_up' item.id %}" class="block-20" style="background-image: url({{ item.image.url }});">
                    </a>
                    <div class="text mt-3 float-right d-block">
                        <div class="d-flex align-items-center mb-3 meta">
                            <p class="mb-0">
                                <span class="mr-2">{{ item.created_at }}</span>
                                <a href="#" class="mr-2">Admin</a>
                                <a href="#" class="meta-chat"><span class="icon-chat"></span> {{ item.views }}</a>
                            </p>
                        </div>
                        <h3 class="heading"><a href="{% url 'blog:views_up' item.id %}">{{ item.title }}</a>
                        </h3>
                        <p>{{ item.content }}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    <div class="row mt-5">
        <div class="col text-center">
            <div class="block-27">
                <ul>
                    {% if page_obj.has_other_pages %}

                    {% if page_obj.has_previous %}
<!--                    <li><a href="?page={{ page_obj.previous_page_number }}"><</a></li>-->
                    <li><a href="?{% url_replace page=page_obj.previous_page_number %}"><</a></li>
                    {% endif %}

                    {% for i in page_obj.paginator.page_range %}

                    {% if page_obj.number == i %}
                    <li class="active"><span>{{ i }}</span></li>
                    {% elif i > page_obj.number|add:-2 and i < page_obj.number|add:2 %}
<!--                    <li><span><a href="?page={{ i }}">{{ i }}</a></span></li>-->
                    <li><span><a href="?{% url_replace page=i %}">{{ i }}</a></span></li>
                    {% endif %}

                    {% endfor %}

                    {% if page_obj.has_next %}
<!--                    <li><a href="?page={{ page_obj.next_page_number }}">&gt;</a></li>-->
                    <li><a href="?{% url_replace page=page_obj.next_page_number %}">&gt;</a></li>
                    {% endif %}

                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/footer.html
{% load static %}
<footer class="ftco-footer ftco-section">
    <div class="container">
        <div class="row mb-5">
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Lets talk about</h2>
                    <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there
                        live the blind texts.</p>
                    <p><a href="#" class="btn btn-primary">Learn more</a></p>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4 ml-md-4">
                    <h2 class="ftco-heading-2">Links</h2>
                    <ul class="list-unstyled">
                        <li><a href="#"><span class="fa fa-chevron-right mr-2"></span>Home</a></li>
                        <li><a href="#"><span class="fa fa-chevron-right mr-2"></span>About</a></li>
                        <li><a href="#"><span class="fa fa-chevron-right mr-2"></span>Services</a></li>
                        <li><a href="#"><span class="fa fa-chevron-right mr-2"></span>Projects</a></li>
                        <li><a href="#"><span class="fa fa-chevron-right mr-2"></span>Contact</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Services</h2>
                    <ul class="list-unstyled">
                        <li><a href="#"><span class="fa fa-chevron-right mr-2"></span>Web Design</a></li>
                        <li><a href="#"><span class="fa fa-chevron-right mr-2"></span>Web Development</a></li>
                        <li><a href="#"><span class="fa fa-chevron-right mr-2"></span>Business Strategy</a></li>
                        <li><a href="#"><span class="fa fa-chevron-right mr-2"></span>Data Analysis</a></li>
                        <li><a href="#"><span class="fa fa-chevron-right mr-2"></span>Graphic Design</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Have a Questions?</h2>
                    <div class="block-23 mb-3">
                        <ul>
                            <li><span class="icon fa fa-map marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span>
                            </li>
                            <li><a href="#"><span class="icon fa fa-phone"></span><span
                                    class="text">+2 392 3929 210</span></a></li>
                            <li><a href="#"><span class="icon fa fa-paper-plane pr-4"></span><span class="text"><span
                                    class="__cf_email__" data-cfemail="375e595158774e58424553585a565e591954585a">[email&#160;protected]</span></span></a>
                            </li>
                        </ul>
                    </div>
                    <ul class="ftco-footer-social list-unstyled mt-2">
                        <li class="ftco-animate"><a href="#"><span class="fa fa-twitter"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="fa fa-facebook"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="fa fa-instagram"></span></a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-center">
                <p>
                    Copyright &copy;<script data-cfasync="false"
                                            src="https://preview.colorlib.com/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script>
                    <script>document.write(new Date().getFullYear());</script>
                    All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by
                    <a href="https://colorlib.com/" target="_blank">Colorlib</a>
                </p>
            </div>
        </div>
    </div>
</footer>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light site-navbar-target"
     id="ftco-navbar">
    <div class="container">
        <a class="navbar-brand" href="/">Clyde<span>.</span></a>
        <button class="navbar-toggler js-fh5co-nav-toggle fh5co-nav-toggle" type="button" data-toggle="collapse"
                data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="oi oi-menu"></span> Menu
        </button>
        <div class="collapse navbar-collapse" id="ftco-nav">
            <ul class="navbar-nav nav ml-auto">
                <li class="nav-item"><a href="/" class="nav-link"><span>Home</span></a></li>
                <li class="nav-item"><a href="/#about-section" class="nav-link"><span>About</span></a></li>
                <li class="nav-item"><a href="/#skills-section" class="nav-link"><span>Skills</span></a></li>
                <li class="nav-item"><a href="/#services-section" class="nav-link"><span>Services</span></a></li>
                <li class="nav-item"><a href="/#projects-section" class="nav-link"><span>Projects</span></a></li>
                <li class="nav-item"><a href="{% url 'blog:blog' %}" class="nav-link"><span>Blogs</span></a></li>
                <li class="nav-item"><a href="/#blog-section" class="nav-link"><span>Blog</span></a></li>
                <li class="nav-item"><a href="/#contact-section" class="nav-link"><span>Contact</span></a></li>
            </ul>
        </div>
    </div>
</nav>

templates/single.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Blog Single{% endblock title %}

{% block content %}
<section class="hero-wrap hero-wrap-2" style="background-image: url({% static 'images/bg_4.jpg' %});"
         data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-center">
            <div class="col-md-9 ftco-animate pb-5 text-center">
                <p class="breadcrumbs"><span class="mr-2"><a href="/">Home / <i
                        class="fa fa-chevron-right"></i></a></span> <span class="mr-2"><a href="blog.html">Blog / <i
                        class="fa fa-chevron-right"></i></a></span> <span>Blog Single <i
                        class="fa fa-chevron-right"></i></span></p>
                <h1 class="mb-0 bread">Blog details</h1>
            </div>
        </div>
    </div>
</section>
<section class="ftco-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 ftco-animate">
                <h2 class="mb-3">{{ blog_obj.title }}</h2>
                <p>{{ blog_obj.content }}</p>
                <div class="tag-widget post-tag-container mb-5 mt-5">
                    <div class="tagcloud">
                        {% for tag in blog_obj.tags.all %}
                        <a href="{% url 'blog:blog' %}?tag={{ tag }}" class="tag-cloud-link">{{ tag.title }}</a>
                        {% endfor %}
                    </div>
                </div>
                <div class="meta">
                    <div><a href="#"><span class="icon-chat"></span>Views of blog: {{ blog_obj.views }}</a></div>
                </div>
                <div class="pt-5 mt-5">
                    {% if blog_obj.commentmodel_set.count <= 1 %}
                    <h4 class="mb-5 font-weight-bold">{{ blog_obj.commentmodel_set.count }} comment</h4>
                    {% else %}
                    <h4 class="mb-5 font-weight-bold">{{ blog_obj.commentmodel_set.count }} comments</h4>
                    {% endif %}
                    <ul class="comment-list">
                        {% for item in blog_obj.commentmodel_set.all %}
                        <li class="comment">
                            <div class="vcard bio">
                                {% if item.avatar %}
                                <img src="{{ item.avatar.url }}" alt="Image placeholder">
                                {% else %}
                                <img src="{% static 'images/avatardefault_92824.png' %}" alt="Image placeholder">
                                {% endif %}
                            </div>
                            <div class="comment-body">
                                <h3>{{ item.name }}</h3>
                                <div class="meta">{{ item.created_at }}</div>
                                <p>{{ item.message }}</p>
                            </div>
                        </li>
                        {% endfor %}
                    </ul>

                    <div class="comment-form-wrap pt-5">
                        <h3 class="mb-5">Leave a comment</h3>
                        <form method="post" class="p-5 bg-light" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="name">Name *</label>
                                <!--                                <input type="text" class="form-control" id="name">-->
                                {{ form.name }}
                            </div>
                            <div class="form-group">
                                <label for="image">Image *</label>
                                <!--                                <input type="image" class="form-control" id="image">-->
                                {{ form.avatar }}
                            </div>
                            <div class="form-group">
                                <label for="email">Email *</label>
                                <!--                                <input type="email" class="form-control" id="email">-->
                                {{ form.email }}
                            </div>
                            <div class="form-group">
                                <label for="website">Website</label>
                                <!--                                <input type="url" class="form-control" id="website">-->
                                {{ form.website }}
                            </div>
                            <div class="form-group">
                                <label for="message">Message</label>
                                <!--                                <textarea name="" id="message" cols="30" rows="10" class="form-control"></textarea>-->
                                {{ form.message }}
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn py-3 px-4 btn-primary">Post Comment</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 sidebar ftco-animate">
                <div class="sidebar-box">
                    <form method="get" action="{% url 'blog:blog' %}?q={{ q }}" class="search-form">
                        <div class="form-group">
                            <span class="icon icon-search"></span>
                            <input type="text" name="q" class="form-control" placeholder="Type a keyword and hit enter">
                        </div>
                    </form>
                </div>
                <div class="sidebar-box ftco-animate">
                    <h3 class="heading-sidebar">Categories</h3>
                    <ul class="categories">
                        {% for category in categories %}
                        <li><a href="{% url 'blog:blog' %}?category={{ category }}">{{ category.title }} <span>({{ category.n }})</span></a></li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="sidebar-box ftco-animate">
                    <h3 class="heading-sidebar">Recent Blog</h3>
                    {% for item in recent_articles %}
                    <div class="block-21 mb-4 d-flex">
                        <a class="blog-img mr-4" style="background-image: url({{ item.image.url }});"></a>
                        <div class="text">
                            <h3 class="heading"><a href="{% url 'blog:views_up' item.id %}">{{ item.title }}</a></h3>
                            <div class="meta">
                                <div><a href="#"><span class="icon-calendar"></span> {{ item.created_at }}</a></div>
                                <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                                <div><a href="#"><span class="icon-chat"></span> {{ item.views }}</a></div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <div class="sidebar-box ftco-animate">
                    <h3 class="heading-sidebar">Tag Cloud</h3>
                    <div class="tagcloud">
                        {% for tag in tags %}
                        <a href="{% url 'blog:blog' %}?tag={{ tag }}" class="tag-cloud-link">{{ tag.title }}</a>
                        {% endfor %}
                    </div>
                </div>

                <div class="sidebar-box ftco-animate">
                    <h3 class="heading-sidebar">Paragraph</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem necessitatibus
                        voluptate quod mollitia delectus aut, sunt placeat nam vero culpa sapiente consectetur
                        similique, inventore eos fugit cupiditate numquam!</p>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}